import type { CardMaster } from '../types';

export const CARD_MASTER: CardMaster[] = [
  // SSR (5)
  {
    id: 'card_001',
    name: '炎帝ファラオン',
    rarity: 'SSR',
    prompt: 'powerful fire emperor pharaoh warrior, golden armor with flame ornaments, surrounded by blazing fire, majestic commanding pose, ancient Egyptian ruins background, dramatic lighting',
    cheerMessage: '世界を焼き尽くす炎も、あなたの意志には敵わない。今日も最高の一日にしよう！',
  },
  {
    id: 'card_002',
    name: '星宮セレスティア',
    rarity: 'SSR',
    prompt: 'divine celestial goddess, flowing cosmic dress covered in stars, long silver hair, glowing golden halo, standing among galaxies and nebula, ethereal serene expression',
    cheerMessage: '星々があなたの道を照らしている。どんな闇の中も恐れることはない！',
  },
  {
    id: 'card_051',
    name: '深淵の魔王ザフィール',
    rarity: 'SSR',
    prompt: 'dark demon lord ruler of the abyss, black and purple armor with glowing cracks, massive dark wings, throne of darkness, crimson eyes, overwhelming presence',
    cheerMessage: '深淵から這い上がった者こそが真の王者。今日も頂点を目指せ！',
  },
  {
    id: 'card_052',
    name: '時の賢者クロノス',
    rarity: 'SSR',
    prompt: 'ancient time wizard sage, flowing silver robes covered in clock gears and hourglasses, long white beard, glowing blue eyes, infinite timeline background',
    cheerMessage: '時間は最大の贈り物。今この瞬間を全力で生きよう！',
  },
  {
    id: 'card_053',
    name: '鳳凰の巫女フェニア',
    rarity: 'SSR',
    prompt: 'divine phoenix priestess, radiant vermilion and gold ceremonial robes, sacred phoenix bird companion, blazing sunset sky, serene powerful expression',
    cheerMessage: '炎から蘇る鳳凰のように、何度でも立ち上がれる力があなたにはある！',
  },
  // SR (10)
  {
    id: 'card_003',
    name: '竜騎士ドラコ',
    rarity: 'SR',
    prompt: 'powerful dragon knight warrior, red and black dragon scale armor, holding flaming lance, purple dragon companion beside, dramatic stormy sky background',
    cheerMessage: '竜と共に戦う者に無敵はない。今日の挑戦も必ず乗り越えられる！',
  },
  {
    id: 'card_004',
    name: '氷姫クリスタリア',
    rarity: 'SR',
    prompt: 'elegant ice princess, pale silver hair, blue crystal crown, white flowing dress with ice crystal decorations, frozen castle and aurora background',
    cheerMessage: '冷静な心こそが最強の武器。あなたなら必ずできる！',
  },
  {
    id: 'card_005',
    name: '雷神ライデン',
    rarity: 'SR',
    prompt: 'powerful thunder god warrior, muscular build, lightning bolt armor, wielding electric hammer, dramatic dark storm clouds with lightning bolts background',
    cheerMessage: '雷が轟くように、あなたの力で世界を揺るがせ！',
  },
  {
    id: 'card_006',
    name: '月光の魔女ルナ',
    rarity: 'SR',
    prompt: 'mysterious moonlight witch, flowing midnight black robe with silver moon and star symbols, silver magic staff with crescent moon, misty forest and full moon background',
    cheerMessage: '月の魔法があなたを守っている。今日も自分を信じて！',
  },
  {
    id: 'card_007',
    name: '鋼の将軍テムジン',
    rarity: 'SR',
    prompt: 'legendary steel armored general, dark imposing plate armor, commanding pose on battlefield, army banners behind, determined fierce expression',
    cheerMessage: '大将は絶対に諦めない。あなたの努力は必ず実を結ぶ！',
  },
  {
    id: 'card_008',
    name: '光の聖女エリア',
    rarity: 'SR',
    prompt: 'holy maiden healer, white and gold battle armor, radiant feathered wings of light, healing golden aura, sacred celestial temple background',
    cheerMessage: '光があなたを包んでいる。今日一日も笑顔でいられますように！',
  },
  {
    id: 'card_054',
    name: '烈風の剣士カゼン',
    rarity: 'SR',
    prompt: 'swift wind swordsman, light leather armor with wind streamers, dual blades, tornado swirling around, mid-air battle pose, dynamic action',
    cheerMessage: '風のように素早く、嵐のように力強く。あなたは誰にも止められない！',
  },
  {
    id: 'card_055',
    name: '鋼鉄の武者ブシオ',
    rarity: 'SR',
    prompt: 'powerful samurai warrior, heavy ornate black and gold armor, katana raised, cherry blossom battlefield, fierce battle cry expression',
    cheerMessage: '鋼の意志を持て。折れない心があれば、どんな壁も破れる！',
  },
  {
    id: 'card_056',
    name: '霊峰の仙人ゼンカイ',
    rarity: 'SR',
    prompt: 'immortal mountain sage, simple flowing white robes, long staff, misty mountain peak above clouds, tranquil enlightened smile, floating lotus petals',
    cheerMessage: '静かな心が最大の力。焦らず一歩一歩、山頂まで歩こう！',
  },
  {
    id: 'card_057',
    name: '紅蓮の踊り子エンブ',
    rarity: 'SR',
    prompt: 'crimson flame dancer performer, flowing scarlet and orange dress, fire fans in hands, dramatic stage with fire effects, passionate expressive performance',
    cheerMessage: '情熱を燃やして踊るように、今日も全力で輝こう！',
  },
  // R (15)
  {
    id: 'card_009',
    name: '森の弓手シルヴァ',
    rarity: 'R',
    prompt: 'skilled forest elf archer, green hooded cloak, elegant longbow, ancient sunlit forest background, arrow ready to fire',
    cheerMessage: '目標を定めたら、迷わず射ろ。あなたの矢は必ず届く！',
  },
  {
    id: 'card_010',
    name: '海賊王レドゥ',
    rarity: 'R',
    prompt: 'young charismatic pirate captain, blue coat, tricorn hat, ocean and sailing ship background, confident smiling expression',
    cheerMessage: '大海原に怖いものはない！今日も冒険を楽しもう。',
  },
  {
    id: 'card_011',
    name: '機械師アルキメ',
    rarity: 'R',
    prompt: 'steampunk engineer inventor, round goggles, gear-covered workshop background, holding blueprints and wrench, Victorian era style',
    cheerMessage: '発明は失敗の積み重ね。今日の挑戦が明日の突破口だ！',
  },
  {
    id: 'card_012',
    name: '砂漠の猫族ナイラ',
    rarity: 'R',
    prompt: 'cat girl desert nomad, orange fur ears and tail, exotic desert outfit with golden jewelry, sandy dunes at sunset background, fierce expression',
    cheerMessage: '砂漠の風のように自由に、あなたらしく生きていい！',
  },
  {
    id: 'card_013',
    name: '風の吟遊詩人カンタ',
    rarity: 'R',
    prompt: 'charming bard musician, colorful patchwork outfit, playing lute instrument, medieval tavern background, joyful performing expression',
    cheerMessage: '歌うように日々を楽しんで。あなたの人生は美しいメロディ！',
  },
  {
    id: 'card_014',
    name: '錬金術士アウルム',
    rarity: 'R',
    prompt: 'mysterious alchemist, golden robe, bubbling potions and glowing flasks, arcane laboratory background, transmutation circle on floor',
    cheerMessage: '努力は金に変わる。今日もコツコツ続けよう！',
  },
  {
    id: 'card_015',
    name: '花の忍者サクラ',
    rarity: 'R',
    prompt: 'female ninja kunoichi, pink outfit with sakura blossom motif, cherry blossom petals swirling, night rooftop background, graceful pose',
    cheerMessage: '桜のように輝いて。あなたの美しさは誰にも止められない！',
  },
  {
    id: 'card_016',
    name: '雪原の狩人フィン',
    rarity: 'R',
    prompt: 'skilled winter hunter, fur-lined coat, snowy tundra landscape, ice bow and arrows, arctic fox companion by side',
    cheerMessage: '厳しい冬を乗り越えた者だけが春を知る。もう少しだ！',
  },
  {
    id: 'card_017',
    name: '炎使いのイフリ',
    rarity: 'R',
    prompt: 'fire mage sorceress, blazing orange flame magic swirling around her, volcano background, intense glowing red eyes',
    cheerMessage: '情熱の炎を絶やすな！あなたの熱量は最強の武器だ。',
  },
  {
    id: 'card_018',
    name: '天空の竜テリアス',
    rarity: 'R',
    prompt: 'majestic sky dragon, shimmering white and gold scales, spread wings soaring above clouds, sunrise background, powerful and graceful',
    cheerMessage: '大空を羽ばたくように、あなたの夢は無限大だ！',
  },
  {
    id: 'card_019',
    name: '古代の巫女ヒミコ',
    rarity: 'R',
    prompt: 'ancient shrine maiden priestess, white and deep red ceremonial robes, floating orbs of spiritual light, misty ancient shrine background',
    cheerMessage: '祈りはいつでも届いている。あなたは見守られている。',
  },
  {
    id: 'card_020',
    name: '電脳ハッカーNEO',
    rarity: 'R',
    prompt: 'cyberpunk hacker character, neon blue glowing eyes, dark hoodie, surrounded by holographic screens and data streams, night city background',
    cheerMessage: 'コードのように、一行一行積み上げれば何でもできる！',
  },
  {
    id: 'card_021',
    name: '深海の人魚マリア',
    rarity: 'R',
    prompt: 'beautiful mermaid princess, shimmering blue-green tail, bioluminescent deep ocean background, exotic sea creatures, flowing long hair',
    cheerMessage: '深海のように深く、あなたの可能性は底知れない！',
  },
  {
    id: 'card_022',
    name: '草原の騎馬士レン',
    rarity: 'R',
    prompt: 'horse rider warrior, leather armor, riding swiftly across vast golden grasslands, wind blowing hair, dramatic sunset horizon',
    cheerMessage: '地平線に向かって走り続けよう。ゴールはすぐそこだ！',
  },
  {
    id: 'card_023',
    name: '宝石細工師のジェム',
    rarity: 'R',
    prompt: 'master gem crafter artisan, workshop full of sparkling precious gems, using precision tools, warm glowing workshop light, proud expression',
    cheerMessage: '原石を磨けば宝石になる。あなた自身が最高の宝石だ！',
  },
  // N (20)
  {
    id: 'card_024',
    name: '村人の英雄タロウ',
    rarity: 'N',
    prompt: 'young village hero boy, simple brown tunic, wooden sword, green meadow background, determined brave expression',
    cheerMessage: '英雄も始まりは普通の村人。今日の一歩が伝説への道！',
  },
  {
    id: 'card_025',
    name: '見習い魔法使いミモ',
    rarity: 'N',
    prompt: 'cute apprentice wizard girl, oversized pointed hat, short magic wand, magical school background, cheerful expression',
    cheerMessage: '未熟でもいい！練習を続ければ必ず上手くなる！',
  },
  {
    id: 'card_026',
    name: '町の鍛冶師ゴード',
    rarity: 'N',
    prompt: 'sturdy town blacksmith, muscular arms, forge and anvil background, holding heavy hammer, hardworking expression',
    cheerMessage: '鉄を打ち続ければ刀になる。継続こそが最大の才能だ！',
  },
  {
    id: 'card_027',
    name: '庭師の精霊フローラ',
    rarity: 'N',
    prompt: 'small garden fairy spirit, tiny delicate wings, surrounded by colorful flowers, watering can, sunny garden background',
    cheerMessage: '毎日コツコツお世話をすれば、いつか美しい花が咲く！',
  },
  {
    id: 'card_028',
    name: '図書館の司書ブック',
    rarity: 'N',
    prompt: 'librarian character, surrounded by towering bookshelves, spectacles and open book, warm study lamp light, scholarly atmosphere',
    cheerMessage: '知識は力。一冊一冊が未来の自分を作る！',
  },
  {
    id: 'card_029',
    name: '厨房のシェフ・ポワロ',
    rarity: 'N',
    prompt: 'confident chef character, tall white chef hat and apron, holding beautifully plated dish, warm busy kitchen background',
    cheerMessage: '美味しい料理も毎日の積み重ね。今日も腕を振るおう！',
  },
  {
    id: 'card_030',
    name: '海辺の釣り師ウミ',
    rarity: 'N',
    prompt: 'relaxed fisherman character, fishing rod, seaside wooden dock, calm ocean view, worn straw hat, peaceful smile',
    cheerMessage: '釣りのように、焦らず待てば必ず結果は来る！',
  },
  {
    id: 'card_031',
    name: '牧場の少年ランチ',
    rarity: 'N',
    prompt: 'cheerful farm boy, denim overalls, red barn and farm animals background, sunny summer day, friendly smile',
    cheerMessage: '牛や羊も毎日のお世話があってこそ。コツコツ続けよう！',
  },
  {
    id: 'card_032',
    name: '街角の占い師オラク',
    rarity: 'N',
    prompt: 'mysterious fortune teller, glowing crystal ball, mystical draped tent, colorful scarves, candles flickering around',
    cheerMessage: '未来はあなたが作るもの。今日の選択が明日を変える！',
  },
  {
    id: 'card_033',
    name: '山小屋の隠者ベア',
    rarity: 'N',
    prompt: 'mountain hermit elder, rugged weathered clothes, cozy wooden mountain cabin, walking staff, snow-peaked mountains visible',
    cheerMessage: '山頂への道も一歩一歩。焦らず着実に登ろう！',
  },
  {
    id: 'card_034',
    name: '港町の船乗りセイル',
    rarity: 'N',
    prompt: 'friendly sailor character, classic blue and white striped shirt, busy harbor background, seagulls flying, anchor tattoo visible',
    cheerMessage: '嵐を乗り越えた船乗りは強い。あなたも必ず越えられる！',
  },
  {
    id: 'card_035',
    name: '森のきこりウッド',
    rarity: 'N',
    prompt: 'hardworking woodcutter, red and black flannel shirt, dense forest background, large axe on shoulder, sturdy build',
    cheerMessage: '木を切る前に斧を磨け。準備こそが成功の鍵！',
  },
  {
    id: 'card_036',
    name: '駆け出し画家ピン',
    rarity: 'N',
    prompt: 'novice painter artist, beret and paint-stained smock, easel in sunlit park, holding colorful palette, inspired expression',
    cheerMessage: 'キャンバスに向き合うように、今日の目標に真剣に！',
  },
  {
    id: 'card_037',
    name: '蜂蜜屋のハニ',
    rarity: 'N',
    prompt: 'beekeeper character, white protective suit and mesh hat, beehives in sunny flower field, jars of honey, sunflowers around',
    cheerMessage: '蜂のように勤勉に働けば、甘い結果が待っている！',
  },
  {
    id: 'card_038',
    name: '夜市の提灯売り',
    rarity: 'N',
    prompt: 'lantern seller at vibrant night market, red and orange lanterns glowing warmly, colorful Asian market background, cheerful vendor',
    cheerMessage: '小さな灯りも集まれば夜を照らせる。あなたの努力は光になる！',
  },
  {
    id: 'card_039',
    name: '見習い薬師ハーブ',
    rarity: 'N',
    prompt: 'herbalist apprentice, herb-covered apron, forest cottage with drying herbs and potion bottles, mortar and pestle in hand',
    cheerMessage: '薬草一つ一つを大切に。小さなことを丁寧にすることが大事！',
  },
  {
    id: 'card_040',
    name: '市場の行商人マーチ',
    rarity: 'N',
    prompt: 'traveling merchant character, fully loaded cart with colorful wares, cobblestone market square, friendly trading smile',
    cheerMessage: '出会う人みんなに笑顔を届けよう。あなたの明るさが周りを元気にする！',
  },
  {
    id: 'card_041',
    name: '砂浜の貝殻拾いシェル',
    rarity: 'N',
    prompt: 'girl collecting shells on sunny beach, light summer dress, golden sandy shore, gentle ocean waves, woven basket of shells',
    cheerMessage: '宝物は足元にある。今日も小さな発見を楽しもう！',
  },
  {
    id: 'card_042',
    name: '宿屋の看板娘イン',
    rarity: 'N',
    prompt: 'cheerful inn hostess girl, practical apron, warm rustic tavern interior, crackling fireplace behind, welcoming smile',
    cheerMessage: 'あなたの笑顔が誰かの疲れを癒す。今日もありがとう！',
  },
  {
    id: 'card_043',
    name: '星観者アストロ',
    rarity: 'N',
    prompt: 'thoughtful stargazer character, brass telescope on hilltop, breathtaking night sky with milky way, peaceful contemplative mood',
    cheerMessage: '星のように輝く未来がある。今夜も夢を見て！',
  },
];

export const CARD_MASTER_BY_ID: Record<string, CardMaster> = Object.fromEntries(
  CARD_MASTER.map(c => [c.id, c])
);

export const CARDS_BY_RARITY = {
  N: CARD_MASTER.filter(c => c.rarity === 'N'),
  R: CARD_MASTER.filter(c => c.rarity === 'R'),
  SR: CARD_MASTER.filter(c => c.rarity === 'SR'),
  SSR: CARD_MASTER.filter(c => c.rarity === 'SSR'),
};
