import type { CardMaster } from '../types';

export const SEASON2_ID = 'season_2';

export const CARD_MASTER: CardMaster[] = [
  // SSR (5)
  {
    id: 'card_101',
    name: '海皇ネプチュロス',
    rarity: 'SSR',
    prompt: 'majestic ocean emperor poseidon, shimmering sapphire and gold scale armor, wielding glowing golden trident, massive tidal wave and glowing bioluminescent sea life background, powerful commanding expression, cinematic lighting',
    cheerMessage: '深海の荒波も、あなたの前進を止めることはできない。今日も堂々と進もう！',
  },
  {
    id: 'card_102',
    name: '創世の女神ヴァルキリア',
    rarity: 'SSR',
    prompt: 'divine creation goddess, six radiant golden wings of light, glowing sacred aura, intricate white marble and gold armor, holding orb of light, starry cosmic sky background, majestic serene expression',
    cheerMessage: 'あなたの中には無限の可能性が眠っている。新しい未来を今日創り出そう！',
  },
  {
    id: 'card_103',
    name: '覇王黒龍ガルガロス',
    rarity: 'SSR',
    prompt: 'dark dragon king warrior, obsidian plate armor with crimson glowing veins, massive dark dragon wings, sword imbued with dark red lightning, volcanic erupted landscape background, intense fierce expression',
    cheerMessage: 'いかなる絶望も、あなたの力で希望に変えられる。覇道を突き進め！',
  },
  {
    id: 'card_104',
    name: '極光の精霊王オーロラ',
    rarity: 'SSR',
    prompt: 'ethereal aurora spirit queen, translucent gown weaving vivid green and violet light, crystal crown, floating above snowy mountains under arctic night sky, glowing particle effects, graceful serene pose',
    cheerMessage: '暗闇が深いほど、あなたの光は一層輝きを増す。自信を持って突き進もう！',
  },
  {
    id: 'card_105',
    name: '太陽神サンクティス',
    rarity: 'SSR',
    prompt: 'glorious sun deity god, brilliant golden sun armor with solar flares, solar crown, wielding a blade of pure sunlight, soaring high above clouds at dawn, radiant warm lighting, epic atmosphere',
    cheerMessage: 'あなたは周囲を照らす太陽そのもの。今日という一日をあなたの熱量で満たそう！',
  },

  // SR (10)
  {
    id: 'card_106',
    name: '疾風の翼アルマ',
    rarity: 'SR',
    prompt: 'swift winged female warrior, feather-accented silver armor, large white wings spread, wielding dual wind blades, mid-air flight pose, bright blue sky with clouds background, dynamic lighting',
    cheerMessage: '追い風に乗ればどこまでも飛べる。追い求め続ければ夢はかならず叶う！',
  },
  {
    id: 'card_107',
    name: '冥界の騎士ハデス',
    rarity: 'SR',
    prompt: 'underworld knight, dark steel armor with soul-blue fire, skull motifs, wielding massive scythe with glowing blade, misty gothic cemetery background, intimidating cold expression',
    cheerMessage: '死線を超えてきたあなたなら大丈夫。どんな試練も跳ね返そう！',
  },
  {
    id: 'card_108',
    name: '翠緑の賢者ルードヴィヒ',
    rarity: 'SR',
    prompt: 'forest archmage elf, emerald embroidered robes, holding gnarled wooden staff topped with glowing green gem, ancient giant tree library background, tranquil wise smile',
    cheerMessage: '積み重ねた知識と経験は裏切らない。焦らず着実に答えを出していこう！',
  },
  {
    id: 'card_109',
    name: '紫電のくノ一カゲロウ',
    rarity: 'SR',
    prompt: 'purple lightning female ninja, sleek dark shinobi outfit with glowing purple lightning trims, dual kunai held in combat stance, full moon night rooftop background, sharp fierce eyes',
    cheerMessage: '静かに、しかし確実に狙いを定める。あなたの集中力なら何でも成し遂げられる！',
  },
  {
    id: 'card_110',
    name: '黄金の槍騎兵ガウェイン',
    rarity: 'SR',
    prompt: 'noble golden lancer knight, polished golden armor, long ornate lance with red banner, mounted on armored white warhorse, sunlit medieval castle background, heroic stance',
    cheerMessage: '正面突破こそが最善の道。自分の選択を信じて、堂々と突き進もう！',
  },
  {
    id: 'card_111',
    name: '機巧の傀儡師ミレイ',
    rarity: 'SR',
    prompt: 'steampunk puppeteer girl, gothic dress, controlling floating mechanical doll guardians with glowing blue energy strings, gear workshop background, confident clever smile',
    cheerMessage: '複雑な問題も一つずつ紐解けば必ず解ける。知恵を絞って乗り越えよう！',
  },
  {
    id: 'card_112',
    name: '星詠みの聖女ステラ',
    rarity: 'SR',
    prompt: 'starlight prophet priestess, flowing navy blue gown with silver constellations, holding glowing armillary sphere, night observatory background, gentle smiling expression',
    cheerMessage: '未来の兆しはすでにあなたの中に。導かれた道を信じて一歩踏み出そう！',
  },
  {
    id: 'card_113',
    name: '焔の銃士ロザリア',
    rarity: 'SR',
    prompt: 'fiery musketeer woman, crimson coat and feathered hat, dual flintlock pistols emitting fiery smoke, burning embers around, tavern background, confident smirk',
    cheerMessage: '引き金を引くのはあなた自身。狙ったチャンスは絶対に逃すな！',
  },
  {
    id: 'card_114',
    name: '樹海の大修道士ゴライアス',
    rarity: 'SR',
    prompt: 'giant forest monk, heavy wooden shoulder guards and beaded necklace, glowing green tattoos, meditation pose on massive mossy stone, sunbeams through forest canopy',
    cheerMessage: '大樹のようにどっしりと構えよう。揺るがない心が勝利を引き寄せる！',
  },
  {
    id: 'card_115',
    name: '夢幻の歌姫セレナ',
    rarity: 'SR',
    prompt: 'ethereal illusion siren singer, flowing iridescent dress, singing with floating glowing musical notes and butterflies around, grand starry stage background, passionate performance',
    cheerMessage: 'あなたの声や思いはきっと誰かに届く。自分らしく表現し続けよう！',
  },

  // R (15)
  {
    id: 'card_116',
    name: '砂漠の暗殺者タリク',
    rarity: 'R',
    prompt: 'desert assassin rogue, light cloth wrappings and leather armor, scimitar curved blade, dust storm background, golden eyes behind mask',
    cheerMessage: '影に潜み、機を待つ。耐え抜いた先に最高の瞬間がやってくる！',
  },
  {
    id: 'card_117',
    name: '氷原の狼騎士ヴォルフ',
    rarity: 'R',
    prompt: 'snow wolf knight, fur-lined steel armor, massive greatsword, standing beside a giant white wolf in blizzard, determined icy gaze',
    cheerMessage: '仲間と共に、極寒の嵐も突き進め。一人の力も合わされば無限大だ！',
  },
  {
    id: 'card_118',
    name: '大樹の精霊ドライアド',
    rarity: 'R',
    prompt: 'nature spirit dryad, dress woven from vines and pink blossoms, glowing green eyes, ancient forest background with floating light specks',
    cheerMessage: '小さな成長も確実な一歩。芽吹いた努力を大切に育もう！',
  },
  {
    id: 'card_119',
    name: '荒野のガンマン・ライアン',
    rarity: 'R',
    prompt: 'cowboy gunslinger, brown leather duster coat, Stetson hat, holding revolver, dusty wild west town at sunset background, calm resolute expression',
    cheerMessage: '迷わずに撃ち抜け。あなたの直感はいつだって正しい！',
  },
  {
    id: 'card_120',
    name: '蒸気技師オットー',
    rarity: 'R',
    prompt: 'steampunk mechanic, brass goggles on forehead, soot-stained clothes, wielding steam-powered wrench, copper pipe factory background',
    cheerMessage: 'どんな不具合も調整次第で動く。少しずつ直していけば大丈夫！',
  },
  {
    id: 'card_121',
    name: '白銀の神官シルヴィア',
    rarity: 'R',
    prompt: 'cleric priestess, white and silver vestments, holding staff topped with glowing cross, holy cathedral interior background, warm gentle light',
    cheerMessage: '疲れた時は無理をしないで。自分自身を癒すことも大切な仕事だよ！',
  },
  {
    id: 'card_122',
    name: '潮風の航海士マリン',
    rarity: 'R',
    prompt: 'young female navigator, blue naval jacket, holding brass spyglass and sea chart, ship deck on open ocean background, bright sunny day',
    cheerMessage: '目的地を見失わなければ大丈夫。風向きが変わっても進み続けよう！',
  },
  {
    id: 'card_123',
    name: '火山鍛冶師イグニス',
    rarity: 'R',
    prompt: 'dwarf blacksmith, heavy leather apron, striking red-hot iron blade on anvil with sparks flying, active volcano cave forge background',
    cheerMessage: '打たれるほど心は強くなる。今日の苦労は未来の鋭い刃になる！',
  },
  {
    id: 'card_124',
    name: '影の召喚士ノワール',
    rarity: 'R',
    prompt: 'dark shadow summoner, hooded black cloak, glowing purple spellbook, shadow panther creature emerging from floor circle, mysterious eyes',
    cheerMessage: '見えない力もあなたの味方。直感を信じて一歩を踏み出そう！',
  },
  {
    id: 'card_125',
    name: '竹林の剣客ハンゾウ',
    rarity: 'R',
    prompt: 'wandering ronin swordsman, traditional straw hat and kimonos, katana slightly unsheathed, dense green bamboo forest background, calm focused gaze',
    cheerMessage: '一瞬の集中が道を開く。雑音を払って自分のやるべきことに集中しよう！',
  },
  {
    id: 'card_126',
    name: '薬草の魔女クロエ',
    rarity: 'R',
    prompt: 'witch herbalist, pointed hat with flowers, stirring green bubbling cauldron, cozy cottage interior filled with hanging dried plants',
    cheerMessage: '試行錯誤の分だけ優しくなれる。あなたの工夫は必ず誰かを救う！',
  },
  {
    id: 'card_127',
    name: '光鱗の重騎士ドレイク',
    rarity: 'R',
    prompt: 'dragon scale guardian, heavy golden and white plate armor, massive tower shield, guarding ancient ruins entrance, steadfast resolute stance',
    cheerMessage: '守るべきものがある人間は強い。今日のあなたも立派にやり遂げられる！',
  },
  {
    id: 'card_128',
    name: '街角の曲芸師ピエロ',
    rarity: 'R',
    prompt: 'cheerful acrobat performer, colorful outfit, juggling glowing crystal balls, cobblestone street crowd background, bright joyful smile',
    cheerMessage: '失敗を恐れず笑顔でチャレンジ！楽しむ気持ちが一番の才能だ！',
  },
  {
    id: 'card_129',
    name: '古文書の探求者アルヴィン',
    rarity: 'R',
    prompt: 'archaeologist scholar, brown vest, magnifying glass, ancient dusty ruin with hieroglyphs background, holding glowing relic, curious expression',
    cheerMessage: '疑問を持つことからすべては始まる。好奇心のままに突き進もう！',
  },
  {
    id: 'card_130',
    name: '天空の舞姫ルチル',
    rarity: 'R',
    prompt: 'sky dancer girl, flowing silk ribbons, leaping gracefully among fluffy white clouds, sunrise sky background, joyful free expression',
    cheerMessage: '自由に、軽やかに！固定観念を捨てれば、もっと高く飛べる！',
  },

  // N (20)
  {
    id: 'card_131',
    name: '街のパン屋クララ',
    rarity: 'N',
    prompt: 'baker girl, white apron, holding basket of freshly baked golden bread loaves, warm sunlit bakery background, welcoming smile',
    cheerMessage: '焼き立てのパンのように、温かく優しい気持ちで今日をはじめよう！',
  },
  {
    id: 'card_132',
    name: '見習い兵士ポック',
    rarity: 'N',
    prompt: 'novice guardsman boy, oversized iron helmet, simple spear, wooden training dummy background, energetic determined face',
    cheerMessage: '小さくても熱い気持ちがあれば十分。今日の訓練も全力でいこう！',
  },
  {
    id: 'card_133',
    name: '鉱山の採掘師ピッケル',
    rarity: 'N',
    prompt: 'hardworking miner, lantern attached to helmet, pickaxe on shoulder, crystal cave background, dusty smiling face',
    cheerMessage: '掘り続けた者だけが鉱石に出会える。愚直な継続を誇ろう！',
  },
  {
    id: 'card_134',
    name: '路地裏の野良猫トモ',
    rarity: 'N',
    prompt: 'cute alley cat, fluffy ginger fur, sitting on cobblestone wall, sunny afternoon background, relaxed peaceful posture',
    cheerMessage: 'たまには力を抜いて日向ぼっこ。自分のペースを守ることが一番大事！',
  },
  {
    id: 'card_135',
    name: '郵便配達員ペティ',
    rarity: 'N',
    prompt: 'young postal messenger, leather satchel full of letters, riding bicycle on countryside road, cheerful waving hand',
    cheerMessage: 'あなたの一言が誰かの元気に届く。今日も温かいメッセージを送ろう！',
  },
  {
    id: 'card_136',
    name: '花屋の少女リリー',
    rarity: 'N',
    prompt: 'florist girl, green apron, holding colorful bouquet of sunflowers and tulips, cozy flower shop background, bright gentle smile',
    cheerMessage: 'どんな花もそれぞれのタイミングで咲く。焦らず自分の花を咲かせよう！',
  },
  {
    id: 'card_137',
    name: '時計塔の掃除係ティモ',
    rarity: 'N',
    prompt: 'clock tower cleaner boy, holding broom, giant brass gears background, sunbeams through window, cheerful working pose',
    cheerMessage: '見えない場所のお手入れが全体を支える。あなたの気配りは伝わっているよ！',
  },
  {
    id: 'card_138',
    name: '羊飼いの少女コレット',
    rarity: 'N',
    prompt: 'young shepherdess, wooden crook staff, surrounded by fluffy white sheep, rolling green hills background, sunny peaceful day',
    cheerMessage: '一歩一歩歩めば遠くまでいける。今日もマイペースに前進しよう！',
  },
  {
    id: 'card_139',
    name: '見習い調剤師レミ',
    rarity: 'N',
    prompt: 'apprentice apothecary boy, holding scale and glass beaker, shelves of dried herbs background, concentrated focused expression',
    cheerMessage: '一つ一つの丁寧な積み重ねが、大きな成果をつくる！',
  },
  {
    id: 'card_140',
    name: '港の荷揚げ屋デリック',
    rarity: 'N',
    prompt: 'strong dock worker, wooden crate on shoulder, sunny harbor with ships background, muscular arms, confident smile',
    cheerMessage: '重い課題も一つずつ運べば必ず片付く。気合を入れていこう！',
  },
  {
    id: 'card_141',
    name: '雨上がりのカエル精霊ケロ',
    rarity: 'N',
    prompt: 'small frog spirit, holding lotus leaf umbrella, wet green hydrangeas and rainbow background, cheerful glossy eyes',
    cheerMessage: '雨の後には必ず綺麗な虹が出る。今日の悩みも明日の糧になる！',
  },
  {
    id: 'card_142',
    name: '夜回りの警備員ノクス',
    rarity: 'N',
    prompt: 'night watchman, holding warm oil lantern, dark quiet cobblestone street background, vigilant friendly posture',
    cheerMessage: '見守ってくれる人がいるから大丈夫。安心して全力を尽くそう！',
  },
  {
    id: 'card_143',
    name: '本火を灯す少年ルーク',
    rarity: 'N',
    prompt: 'young lamplighter boy, long pole lighting street lanterns at dusk, cozy European town background, warm orange light glow',
    cheerMessage: 'あなたの小さな親切が、誰かの心を温かく照らしている！',
  },
  {
    id: 'card_144',
    name: '風車小屋の管理人ペーター',
    rarity: 'N',
    prompt: 'windmill keeper, blue overalls, large wooden windmill under blue sky with white clouds background, waving friendly hand',
    cheerMessage: '風が吹けば車輪は回る。焦らずタイミングを待つのも大切！',
  },
  {
    id: 'card_145',
    name: '果樹園の摘み手ポモナ',
    rarity: 'N',
    prompt: 'fruit picker girl, straw hat, basket overflowing with ripe red apples, sunlit orchard background, joyful expression',
    cheerMessage: '努力の果実が実る時期はもうすぐ。収穫を楽しみに進もう！',
  },
  {
    id: 'card_146',
    name: '川辺の洗濯屋モネ',
    rarity: 'N',
    prompt: 'laundry girl, hanging fresh white linens on clothesline, sparkling river and green field background, bright summer sunshine',
    cheerMessage: '心を洗い流してリフレッシュ！まっさらな気持ちで今日を始めよう！',
  },
  {
    id: 'card_147',
    name: '見習い彫刻家カーヴ',
    rarity: 'N',
    prompt: 'young sculptor, chisel and mallet in hand, stone marble block in workshop background, focused determined eyes',
    cheerMessage: '不要なものを削ぎ落とせば、真の姿が見えてくる。信念を研ぎ澄ませ！',
  },
  {
    id: 'card_148',
    name: '旅の靴職人コブラー',
    rarity: 'N',
    prompt: 'shoemaker artisan, sitting at workbench, stitching sturdy leather boots, cozy workshop interior, proud smile',
    cheerMessage: '良い靴が良い場所へ連れて行ってくれる。しっかり足元を固めて歩もう！',
  },
  {
    id: 'card_149',
    name: '木こりの見習いルバー',
    rarity: 'N',
    prompt: 'apprentice lumberjack boy, small axe over shoulder, pine forest background, energetic bright smile',
    cheerMessage: '大きな木も一斧ずつ。日々の積み重ねが一番の近道！',
  },
  {
    id: 'card_150',
    name: '静かな星空の観測者オルガ',
    rarity: 'N',
    prompt: 'young girl stargazing, wrapped in cozy blanket, sitting on grassy hill, starry night sky with shooting star background, peaceful dreaminess',
    cheerMessage: '今日一日よく頑張ったね。今夜は良い夢を見て明日へ備えよう！',
  },
];

export const CARD_MASTER_BY_ID: Record<string, CardMaster> = Object.fromEntries(
  CARD_MASTER.map(c => [c.id, c])
);

export const CARDS_BY_RARITY = {
  N: CARD_MASTER.filter(c => c.rarity === 'N'),
  R: CARD_MASTER.filter(c => c.rarity === 'R'),
  SR: CARD_MASTER.filter(c => c.rarity === 'SR'),
  SSR: CARD_MASTER.filter(c => c.rarity === 'SSR'),
};